# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: 9131fee9-bd07-4379-aa0c-31239b5a2098
  namespace: 9131fee9-bd07-4379-aa0c-31239b5a2098
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: true
    instanceType: t3.micro
    disableIngressRules: false
    allowedCIDRBlocks:
      - 127.0.0.1/32
