# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
subjects:
- kind: ServiceAccount
  name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
  namespace: 9131fee9-bd07-4379-aa0c-31239b5a2098
