# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws-check
  namespace: 9131fee9-bd07-4379-aa0c-31239b5a2098
spec:
  template:
    metadata:
      name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
    spec:
      serviceAccountName: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 9131fee9-bd07-4379-aa0c-31239b5a2098
        - 9131fee9-bd07-4379-aa0c-31239b5a2098
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 9131fee9-bd07-4379-aa0c-31239b5a2098-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
